"""initial schema

Revision ID: d34d793cdf83
Revises: 
Create Date: 2026-04-28 15:30:02.096389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd34d793cdf83'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('population', sa.BigInteger(), nullable=True),
    sa.Column('child_pop_under_15', sa.BigInteger(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['admin_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_admin_units_geometry ON admin_units USING gist (geometry)")
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('payload_jsonb', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('config_jsonb', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diseases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vector_species', sa.String(length=255), nullable=True),
    sa.Column('incubation_days', sa.Integer(), nullable=True),
    sa.Column('climate_params_jsonb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('sensor_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('schema_jsonb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.Column('settings_jsonb', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('translations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('field', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('verticals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('case_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('disease_id', sa.UUID(), nullable=False),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('reported_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.ForeignKeyConstraint(['disease_id'], ['diseases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('climate_features',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('precip_mm', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('planned_at', sa.DateTime(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('target_disease_id', sa.UUID(), nullable=True),
    sa.Column('training_data_ref', sa.String(length=512), nullable=True),
    sa.Column('metrics_jsonb', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['target_disease_id'], ['diseases.id'], ),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite_acquisitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.Column('cloud_cover_pct', sa.Float(), nullable=True),
    sa.Column('storage_uri', sa.String(length=512), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sensors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_type_id', sa.UUID(), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_jsonb', sa.JSON(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.ForeignKeyConstraint(['sensor_type_id'], ['sensor_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_sensors_location ON sensors USING gist (location)")
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=True),
    sa.Column('locale', sa.String(length=10), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flights',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('data_source_id', sa.UUID(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('operator_id', sa.UUID(), nullable=True),
    sa.Column('mission_path_jsonb', sa.JSON(), nullable=True),
    sa.Column('payload_type', sa.String(length=30), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('admin_unit_id', sa.UUID(), nullable=False),
    sa.Column('target_date', sa.DateTime(), nullable=False),
    sa.Column('target_horizon', sa.String(length=10), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('uncertainty', sa.Float(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['admin_unit_id'], ['admin_units.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellite_detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('acquisition_id', sa.UUID(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('promoted', sa.String(length=10), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['acquisition_id'], ['satellite_acquisitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_satellite_detections_geometry ON satellite_detections USING gist (geometry)")
    op.create_table('sensor_readings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sensor_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('payload_jsonb', sa.JSON(), nullable=True),
    sa.Column('temp_c', sa.Float(), nullable=True),
    sa.Column('humidity_pct', sa.Float(), nullable=True),
    sa.Column('rainfall_mm', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prediction_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('recipient_role', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('imagery',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('flight_id', sa.UUID(), nullable=False),
    sa.Column('captured_at', sa.DateTime(), nullable=True),
    sa.Column('storage_uri', sa.String(length=512), nullable=False),
    sa.Column('metadata_jsonb', sa.JSON(), nullable=True),
    sa.Column('geom_bbox', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('imagery_type', sa.String(length=20), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['flight_id'], ['flights.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_imagery_geom_bbox ON imagery USING gist (geom_bbox)")
    op.create_table('detections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('imagery_id', sa.UUID(), nullable=True),
    sa.Column('vertical_id', sa.UUID(), nullable=True),
    sa.Column('detection_type', sa.String(length=50), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['imagery_id'], ['imagery.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ),
    sa.ForeignKeyConstraint(['vertical_id'], ['verticals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_detections_geometry ON detections USING gist (geometry)")
    op.create_table('interventions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('detection_id', sa.UUID(), nullable=True),
    sa.Column('mission_id', sa.UUID(), nullable=True),
    sa.Column('intervention_type', sa.String(length=50), nullable=False),
    sa.Column('target_geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('larvicide_ml', sa.Float(), nullable=True),
    sa.Column('operator_notes', sa.Text(), nullable=True),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['detection_id'], ['detections.id'], ),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.execute("CREATE INDEX IF NOT EXISTS idx_interventions_target_geometry ON interventions USING gist (target_geometry)")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS idx_interventions_target_geometry")
    op.drop_table('interventions')
    op.execute("DROP INDEX IF EXISTS idx_detections_geometry")
    op.drop_table('detections')
    op.execute("DROP INDEX IF EXISTS idx_imagery_geom_bbox")
    op.drop_table('imagery')
    op.drop_table('alerts')
    op.drop_table('sensor_readings')
    op.execute("DROP INDEX IF EXISTS idx_satellite_detections_geometry")
    op.drop_table('satellite_detections')
    op.drop_table('predictions')
    op.drop_table('flights')
    op.drop_table('users')
    op.execute("DROP INDEX IF EXISTS idx_sensors_location")
    op.drop_table('sensors')
    op.drop_table('satellite_acquisitions')
    op.drop_table('models')
    op.drop_table('missions')
    op.drop_table('climate_features')
    op.drop_table('case_reports')
    op.drop_table('verticals')
    op.drop_table('translations')
    op.drop_table('tenants')
    op.drop_table('sensor_types')
    op.drop_table('diseases')
    op.drop_table('data_sources')
    op.drop_table('audit_log')
    op.execute("DROP INDEX IF EXISTS idx_admin_units_geometry")
    op.drop_table('admin_units')
    # ### end Alembic commands ###
